# Otras estructuras de datos en python

Datos estructurados
* Corchetes > Listas
* Parentesis > Tuplas  (Inalterables)
* Llaves > Diccionarios

In [8]:
a = "Hola"

In [12]:
a = 1
b = 5

# 1 = es una asignacion
b = a

In [15]:
b

1

In [16]:
a

1

In [17]:
# 2 igualees == no es una asignacion, es una pregunta

a = 4
b = 8

a == b

False

In [18]:

b == a

False

In [20]:
a = 11
b = 13


c = a == b

In [21]:
c

False

In [22]:
c = b == a

In [23]:
a

11

In [5]:
import math

help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [4]:
math.__dict__

{'__name__': 'math',
 '__doc__': 'This module provides access to the mathematical functions\ndefined by the C standard.',
 '__package__': '',
 '__loader__': _frozen_importlib.BuiltinImporter,
 '__spec__': ModuleSpec(name='math', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'),
 'acos': <function math.acos(x, /)>,
 'acosh': <function math.acosh(x, /)>,
 'asin': <function math.asin(x, /)>,
 'asinh': <function math.asinh(x, /)>,
 'atan': <function math.atan(x, /)>,
 'atan2': <function math.atan2(y, x, /)>,
 'atanh': <function math.atanh(x, /)>,
 'ceil': <function math.ceil(x, /)>,
 'copysign': <function math.copysign(x, y, /)>,
 'cos': <function math.cos(x, /)>,
 'cosh': <function math.cosh(x, /)>,
 'degrees': <function math.degrees(x, /)>,
 'erf': <function math.erf(x, /)>,
 'erfc': <function math.erfc(x, /)>,
 'exp': <function math.exp(x, /)>,
 'expm1': <function math.expm1(x, /)>,
 'fabs': <function math.fabs(x, /)>,
 'factorial': <function math.factorial(x, /)>,

In [26]:
if = 5


SyntaxError: invalid syntax (<ipython-input-26-1a9bb92cc795>, line 1)

Datos estructurados
* Corchetes > Listas
* Parentesis > Tuplas  (Inalterables)
* Llaves > Diccionarios

# Listas

Las listas son simplemente un conjunto de datos y se lo define entre corchetes con sus elementos separados con coma
<br>Es lo que en otros lenguajes como Java, Php, C++ se los conoce como Arrays o Arreglos

Una lista vacía se la escribe así

In [1]:
lista_vacia = list()
lista_vacia

[]

O así

In [2]:
lista_vacia = []
lista_vacia

[]

In [3]:
type(lista_vacia)

list

In [1]:
lista_str = ["Yo",'me','llamo','Juan']
lista_str

['Yo', 'me', 'llamo', 'Juan']

In [28]:
lista_comb = ['Yo','me','llamo','Juan', 1,2,3, False, True]
lista_comb

['Yo', 'me', 'llamo', 'Juan', 1, 2, 3, False, True]

In [29]:
type(lista_comb)

list

In [30]:
len(lista_comb)

9

In [32]:
lista = [1,2,3,4]
sum(lista)

10

In [35]:
palabra1 = "Juan"
palabra2 = "Pablo"
palabra1 + palabra2

'JuanPablo'

Una lista con los numeros del 1 al 4 se la puede definir asi:

In [3]:
lista = ["1","2,3,4"]
print(lista)

['1', '2,3,4']


In [5]:
numero1 = 10
numero2 = 20

numero1 = numero1 + numero2
numero1

30

In [6]:
numero1 = 10
numero2 = 20

numero1 += numero2
numero1

30

In [7]:
numero1 = 10
numero2 = 20

numero1 *= numero2
numero1

200

In [8]:
numero1 = 10
numero2 = 20

numero1 /= numero2
numero1

0.5

O así

In [15]:
lista = list([1,2,3,4])
print(lista)

[1, 2, 3, 4]


In [16]:
type(lista)

list

In [17]:
lista = lista + [5,6]
lista

[1, 2, 3, 4, 5, 6]

In [18]:
lista += [7]
lista

[1, 2, 3, 4, 5, 6, 7]

In [19]:
lista = lista + [8]
lista

[1, 2, 3, 4, 5, 6, 7, 8]

In [11]:
lista = lista + 9
lista

TypeError: can only concatenate list (not "int") to list

In [20]:
lista = lista + ['Palabra',True]
lista += lista
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 'Palabra', True, 1, 2, 3, 4, 5, 6, 7, 8, 'Palabra', True]


In [21]:
stopLoss = 100

stopLoss *= 1.1

In [22]:
lista = [1,2,3,4,"Hola", [1,2,3]]
lista

[1, 2, 3, 4, 'Hola', [1, 2, 3]]

### Acceder a datos de listas

In [23]:
lista = ['Hola', 'Como', 'Estas?']
lista

['Hola', 'Como', 'Estas?']

In [24]:
lista[0]

'Hola'

In [25]:
lista[1]

'Como'

### Intervalos

[ desde : hasta : paso ]

* El desde siempre es inclusive
* El hasta es siempre exclusive

In [27]:
lista = [23,6,3,9,4,12,0]

lista[1:4]

[6, 3, 9]

In [28]:
lista[1:4:2]

[6, 9]

In [29]:
lista = [0,1,2,3,4,5,6,7,8,9,10]

lista[0::3]

[0, 3, 6, 9]

In [30]:
lista[:-2]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [34]:
lista[-1]

10

In [35]:
len(lista)

11

In [38]:
a = 4

lista[a:-1]

[4, 5, 6, 7, 8, 9]

In [43]:
lista = [1,2,3,[[1,2,3,4,5],2]]

lista[3][0][2:4]

[3, 4]

### Lista con rangos

In [47]:
lista  = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
tabla7 = list(range(0,120,7))
tabla7

[0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119]

Funciones de listas y otros
* len
* sum

Métodos de listas
* index(n) (devuelve el orden dentro de la lista del elemento "n")
* count (cuenta la cantidad de elementos)
* sort(reverse=False)
* append (agrega un valor al final)
* extend (agregaega una lista entera de valores)
* insert(x, "n")  (inserta el elemento "n" en la posicion "x")
* pop  ("n") "saca" el elemento "n" y me lo devuelve como return
* reverse   (invierte el orden dado)
* clear() (borra los elementos de la lista)

In [61]:
lista = list(range(7))


prom = sum(lista)/len(lista)
prom

3.0

In [64]:
lista

[0, 1, 2, 3, 4, 5, 6]

In [66]:
lista.count(4)

1

In [67]:
lista += [4,4]
lista

[0, 1, 2, 3, 4, 5, 6, 4, 4]

In [68]:
lista.count(4)

3

In [71]:
lista = [23.1, 23.3, 23.2, 23, 23.25]

lista.index(23.2)

2

In [74]:
precioNuevo = 23.5

lista.append(precioNuevo)

lista

[23.1, 23.3, 23.2, 23, 23.25, 23.5, 23.5]

In [75]:
precioNuevo = [23.5,23.55]

lista.append(precioNuevo)

lista

[23.1, 23.3, 23.2, 23, 23.25, 23.5, 23.5, [23.5, 23.55]]

In [76]:
precioNuevo

[23.5, 23.55]

In [95]:
precioNuevo = 23.75

resultado =  lista.insert(0, precioNuevo)

lista

[23.75,
 23.75,
 23.75,
 23.75,
 23.75,
 23.1,
 23.3,
 23.2,
 23,
 23.25,
 23.5,
 23.5,
 [23.5, 23.55],
 23.75]

In [96]:
print(resultado)

None


In [93]:
resultado = len(lista)

In [94]:
resultado

13

In [97]:
lista

[23.75,
 23.75,
 23.75,
 23.75,
 23.75,
 23.1,
 23.3,
 23.2,
 23,
 23.25,
 23.5,
 23.5,
 [23.5, 23.55],
 23.75]

In [101]:
lista = [1,2,3]
lista

[1, 2, 3]

In [102]:
resultado = lista.pop()
resultado

3

In [103]:
lista

[1, 2]

In [104]:
lista = [1,2,3,4,5]

resultado = lista.pop(3)
resultado

4

In [105]:
lista

[1, 2, 3, 5]

### Truco para reordenar

In [106]:
lista = [1,2,3,4,5,6]
listaR = lista[::-1]

lista

[1, 2, 3, 4, 5, 6]

In [107]:
listaR

[6, 5, 4, 3, 2, 1]

In [12]:
resultadoAppend = lista.append('hola')

In [13]:
lista

[1, 2, 3, 4, 5, 6, 7, 4, 4, 5, 'hola']

In [14]:
print(resultadoAppend)

None


In [15]:
lista

[1, 2, 3, 4, 5, 6, 7, 4, 4, 5, 'hola']

In [16]:
resultadoPop = lista.pop(0)

In [17]:
lista

[2, 3, 4, 5, 6, 7, 4, 4, 5, 'hola']

In [18]:
print(resultadoPop)

1


In [19]:
palabra = 'hola'
palabraL = list(palabra)
palabraL

['h', 'o', 'l', 'a']

In [20]:
lista

[2, 3, 4, 5, 6, 7, 4, 4, 5, 'hola']

In [21]:
lista = [1,4,8,3,7,0,14,5,12,122,3,44]
lista.sort(reverse=False)
lista

[0, 1, 3, 3, 4, 5, 7, 8, 12, 14, 44, 122]

In [22]:
listaLoca = [1,2,'tres',[1,2,3],[4,5,6],[],lista]
listaLoca

[1,
 2,
 'tres',
 [1, 2, 3],
 [4, 5, 6],
 [],
 [0, 1, 3, 3, 4, 5, 7, 8, 12, 14, 44, 122]]

In [23]:
listaLoca.append(listaLoca)

In [24]:
listaLoca

[1,
 2,
 'tres',
 [1, 2, 3],
 [4, 5, 6],
 [],
 [0, 1, 3, 3, 4, 5, 7, 8, 12, 14, 44, 122],
 [...]]

### Slicing de una lista

### Como acceder a elementos:
<br>[desde:hasta:step]

In [25]:
lista = [1,2,3,4,5,6,7,8,9,10]

In [26]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [27]:
lista[::]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
lista[3:6:1]

[4, 5, 6]

In [29]:
lista[:6:2]

[1, 3, 5]

In [30]:
lista[:6:3]

[1, 4]

In [31]:
lista[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


* FIFO
* LIFO

In [110]:
lista = [1,2,3,4]

lista[0] = 'Juan'
lista

['Juan', 2, 3, 4]

### Tuplas

In [111]:
tupla = (1,2,3,4)

tupla[0]

1

In [112]:
tupla[0] = 'Juan'

TypeError: 'tuple' object does not support item assignment

In [114]:
type(tupla)

tuple

In [115]:
tupla

(1, 2, 3, 4)

In [116]:
precios = [23.1, 23.3, 23.2, 23, 23.25]

preciosUp = precios * 1.05
preciosUp

TypeError: can't multiply sequence by non-int of type 'float'

### Operatoria algebraica con listas

Si queremos por ejemplo multiplicar todos los valores de una lista por "k" o sumarles un escalar o cosas por el estilo, vamos a tener que transformar nuestra lista en un array  de numpy
<br><br>En realidad mayoritariamente en el curso vamos a usar matrices, y para ello la liibrería pandas que ya veremos en unas clases, pero como proxy a ello les adelanto su librería antecesora que es numpy

Transformamos una lista en un arreglo de numpy

In [117]:
import numpy as np

In [118]:
precios = [23.1, 23.3, 23.2, 23, 23.25]

precios = np.array(precios)
precios

array([23.1 , 23.3 , 23.2 , 23.  , 23.25])

In [119]:
preciosUp = precios * 1.05
preciosUp

array([24.255 , 24.465 , 24.36  , 24.15  , 24.4125])

In [121]:
precios.std()

0.10770329614269003

In [125]:
np.median(precios)

23.2

In [122]:
precios.mean()

23.17

In [123]:
preciosUp.mean()

24.328500000000002

In [124]:
preciosUp.std()

0.11308846094982458

In [120]:
lista = [1,2,3,4,5,16]
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5, 16])

In [34]:
type(arreglo)

numpy.ndarray

In [35]:
arreglo/2

array([0.5, 1. , 1.5, 2. , 2.5, 8. ])

In [36]:
arreglo*2

array([ 2,  4,  6,  8, 10, 32])

In [37]:
arreglo-11

array([-10,  -9,  -8,  -7,  -6,   5])

#### Simular la cuadratica -3x^2 + 2x -5

In [38]:
cuadratica = -3 * arreglo**2 + 2*arreglo -5
cuadratica

array([  -6,  -13,  -26,  -45,  -70, -741])

In [39]:
arr2 = arreglo**2
arr2/arreglo

array([ 1.,  2.,  3.,  4.,  5., 16.])

In [40]:
arreglo

array([ 1,  2,  3,  4,  5, 16])

Desvio EStandar

In [41]:
arreglo.std()

5.013869652163774

MEdia aritmetica

In [42]:
arreglo.mean()

5.166666666666667

Mediana

In [43]:
np.median(arreglo)

3.5

In [44]:
arreglo

array([ 1,  2,  3,  4,  5, 16])

In [45]:
arreglo.max()

16

In [46]:
np.argmax(arreglo)

5

In [47]:
tupla = (2,3,4,5)
tupla[:3:2]

(2, 4)

In [48]:
lista = [1,2,3,4,5,16,3,4,5,4,5,4,4,4]
lista.count(4)

6

In [130]:
listaA = [1,2,3]
listaB = "[1,2,3]"

In [131]:
listaA[0]

1

In [136]:
listaB[0:4]

'[1,2'

In [137]:
nombre = 'Juan Pablo'
nombre[1]

'u'

# Diccionarios

Un diccionario es una estructura Clave=>Valor
<br>Por ejemplo en lugar de tener un listado de las notas de mis alumnos, podria tener un diccionario con la nota asignada al nombre de cada uno

### Estruuctura del diccionario

* Abre con: {
* Cierra con: }
* Los elementos se separan con comas
* Los elementos del diccionario tienen clave y valor
* La clave se escribe entre comillas preferentemente
* EL valor se escribe entre comillas solo si es un string
* Entre clave y valor va un ":" 

In [3]:
diccionario = {"ALUA":29.35 , "BBAR":120.85 , "BMA":265.2 , "BYMA":[290,299]}
type(diccionario)

dict

In [50]:
print(diccionario)

{'ALUA': 29.35, 'BBAR': 120.85, 'BMA': 265.2, 'BYMA': [290, 299]}


<br>
Dos Formas de Acceder a los valores de una clave de un diccionario

In [51]:
print(diccionario['BBAR'])

120.85


In [52]:
print(diccionario.get('BBAR'))

120.85


In [1]:
rta = diccionario['YPFD']
print(rta)

NameError: name 'diccionario' is not defined

In [4]:
rta = diccionario.get('BYMA', 15)
print(rta)

[290, 299]


Supongamos que sabemos que podria no estar el ticker buscado en el diccionario
<br>Para ello conviene usar el método get, ya que tiene un valor por default en caso que el indice buscado no se encuentre para evitar que tire error el programa, ese valor por default es <b>None</b> es decir un dato nulo pero como decía no me tira error

In [55]:
print(diccionario.get('FRAN'))

None


Asimismo puedo elegir el valor por default que me devuelva en caso de no encontrar el indice en el diccionario, es el segundo argumento que no es obligatorio

In [56]:
print(diccionario.get('FRAN',0))

0


<br>
Accedemos por separado a las Claves y Valores

In [138]:
keys = diccionario.keys()
print(keys)

dict_keys(['ALUA', 'BBAR', 'BMA', 'BYMA'])


In [58]:
values = diccionario.values()
print(values)

dict_values([29.35, 120.85, 265.2, [290, 299]])


In [59]:
values = list(diccionario.values())
print(values)

[29.35, 120.85, 265.2, [290, 299]]


Accedemos a los pares Clave=>Valor

In [147]:
items = diccionario.items()
print(items)

dict_items([('ALUA', 29.35), ('BBAR', 120.85), ('BMA', 265.2), ('BYMA', [290, 299])])


In [61]:
items = diccionario.items()
print(list(items)[0])

('ALUA', 29.35)


In [143]:
list(keys)

['ALUA', 'BBAR', 'BMA', 'BYMA']

In [144]:
list(keys)[1]

'BBAR'

In [151]:
tuplaBBAR = list(items)[1]
tuplaBBAR

('BBAR', 120.85)

In [153]:
tuplaBBAR[1]

120.85

In [154]:
diccionario

{'ALUA': 29.35, 'BBAR': 120.85, 'BMA': 265.2, 'BYMA': [290, 299]}

In [159]:
diccionario['BYMA']

[290, 299]

### Pop
<small>
    Tomar un Elemento y borrarlo pasando la clave, funciona igual que en las listas, aqui devuelve solo el valor, no la clave
</small>

In [62]:
diccionario = {"ALUA":29.35,"BBAR":120.85,"BMA":265.2,"BYMA":295}
itemTomado = diccionario.pop("BBAR")
print(itemTomado)
print(diccionario)

120.85
{'ALUA': 29.35, 'BMA': 265.2, 'BYMA': 295}


### Update
<small>
    Actualiza los valores de un diccionario segun las coincidencias de las claves del segundo
</small>

In [63]:
diccionario1 = {"ALUA":29.35,"BBAR":120.85,"BMA":265.2,"BYMA":295}
diccionario2 = {"BYMA":290,"CEPU":29,"COME":3,"CRES":40.7}
diccionario1.update(diccionario2)
print(diccionario1)

{'ALUA': 29.35, 'BBAR': 120.85, 'BMA': 265.2, 'BYMA': 290, 'CEPU': 29, 'COME': 3, 'CRES': 40.7}


### Insertar nuevo elemento a un diccionario

In [160]:
dic1 = {"ALUA":29.35,"BBAR":120.85,"BMA":265.2,"BYMA":295}
dic1["BYMA"] = 29
print(dic1)

{'ALUA': 29.35, 'BBAR': 120.85, 'BMA': 265.2, 'BYMA': 29}


In [161]:
dic1

{'ALUA': 29.35, 'BBAR': 120.85, 'BMA': 265.2, 'BYMA': 29}

In [162]:
dic1['BMA']

265.2

In [165]:
dic1['ALUA'] = 29.50

In [166]:
dic1

{'ALUA': 29.5, 'BBAR': 120.85, 'BMA': 265.2, 'BYMA': 29, 'YPF': 500}

In [167]:
dic1['YPF']

500

In [168]:
dic1['AAPL']

KeyError: 'AAPL'

In [169]:
dic1['AAPL'] = 1

In [170]:
dic1

{'ALUA': 29.5, 'BBAR': 120.85, 'BMA': 265.2, 'BYMA': 29, 'YPF': 500, 'AAPL': 1}